acl allowed_sites dstdomain "/etc/squid/allowed_domains.txt"

acl SSL_ports port 443
acl CONNECT method CONNECT

http_access deny CONNECT !SSL_ports
http_access allow CONNECT allowed_sites SSL_ports
http_access allow allowed_sites
http_access deny all

http_port 3128
cache deny all
forwarded_for off
dns_nameservers 8.8.8.8 8.8.4.4
